permalink: /:year/:month/:day/:title
paginate: 10
markdown: redcarpet
redcarpet:
   extensions: ["hard_wrap","autolink","tables","fenced_code_blocks","disable_indented_code_blocks","no_intra_emphasis","space_after_headers","underline"]

# 作者信息
author: 
  name: jasee
  email: jaseetao@gmail.com
  link: http://opjasee.com
  weibo: http://weibo.com/justatree
  github: http://github.com/jasee

# 站点信息
title: jasee的博客 
description: 君子生非异也，善假于物也 
url: http://opjasee.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/upload/avatar/avatar.png
favicon: /public/upload/avatar/favicon.ico

# google analytics 设置
ga:
  id: UA-44312631-1
  url: opjasee.com

# disqus 设置
disqus:
  shortname: jasee

# 主题设置，自动激活某个标签
active: 运维

# 中文本地化
locals:
  tags: 标签
  about: 关于
